### ISSUE TITLE
config_temperatureUnits is not defined

### ISSUE THREAD

**Issue by jaredjorgens** [daymondm/homebridge-vivint#9]
I am not using a thermostat with my Vivint system, I took the latest update (1.2.2) and I am getting this error: 

```
10/13/2020, 2:25:03 PM [Vivint] Error while bootstrapping accessories: ReferenceError: config_temperatureUnits is not defined
    at Thermostat.getTemperatureDisplayUnits (/home/hoobs/.hoobs/node_modules/@balansse/homebridge-vivint/lib/accessories/thermostat.js:224:7)
    at Thermostat.notify (/home/hoobs/.hoobs/node_modules/@balansse/homebridge-vivint/lib/accessories/thermostat.js:266:29)
    at Thermostat.handleSnapshot (/home/hoobs/.hoobs/node_modules/@balansse/homebridge-vivint/lib/device.js:46:12)
    at DeviceSet.handleSnapshot (/home/hoobs/.hoobs/node_modules/@balansse/homebridge-vivint/lib/device_set.js:61:47)
    at /home/hoobs/.hoobs/node_modules/@balansse/homebridge-vivint/index.js:103:25
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by balansse** [comment]
Please update to the latest version 1.3.1 and the issue should disappear!
